### ISSUE TITLE
Change Home Menu 

### ISSUE THREAD

**Issue by kerningcultures** [mstdfr/mefp-website#1]
Insert two new tabs: 
<img width="758" alt="screen shot 2018-12-30 at 10 37 06 am" src="https://user-images.githubusercontent.com/45941301/50550132-f4f8a980-0c1e-11e9-9aa5-480fa0872d7c.png">

(1) Newsletters
(2) [Studios](https://docs.google.com/spreadsheets/d/1FaLYvnzgHoJoL9_p33DWizak1OOQitgqRtK1ece1Um0/edit#gid=0)

Newsletters Page:
(blog, updated monthly to reflect quick snapshot and link to that month's newsletter)
[**Issue 1: November 2018]**(https://mailchi.mp/eb71d8e12a51/thank-you-129087)
- To Patreon or to not Patreon?
- Anghami and its upcoming push of podcasts
- Podcast Spotlight: Yalla, the newest podcast network
- Out and About

**[Issue 2: December 2018]**(https://mailchi.mp/a0a7f958213e/me-podcast-forum-december-2018)
- Arabic newsletter
- Spotify Arabia launches
- Podcast Spotlight: Beyond Podcast
- Out and About

**Comment by rtaibah** [comment]
Started working on this on a separate branch. The logic is there, just need to add some styling.

https://github.com/mstdfr/mefp-website/tree/newsletter-updates

**Comment by rtaibah** [comment]
Done, and deployed.
