### ISSUE TITLE
Delete Newsletter Subscription widget 

### ISSUE THREAD

**Issue by kerningcultures** [mstdfr/mefp-website#3]
<img width="754" alt="screen shot 2018-12-30 at 10 38 53 am" src="https://user-images.githubusercontent.com/45941301/50550147-4f920580-0c1f-11e9-809f-8dae27e20d04.png">

**Comment by rtaibah** [comment]
How will people subscribe then? @kerningcultures

**Comment by rtaibah** [comment]
Nevermind I guess #4 addresses that. Fixed.
