### ISSUE TITLE
Change About Copy

### ISSUE THREAD

**Issue by kerningcultures** [mstdfr/mefp-website#4]
Delete everything under "About", replace with:

**About**
We are a team of independent podcasters. We’re passionate about building the ecosystem across the Middle East and North Africa. We host live podcast forums and a monthly newsletter. 

**How to Get Involved:**
Sign up for the Newsletter

[Arabic](https://mepodcastforum.us19.list-manage.com/subscribe?u=effbe51b005308df15c77177b&id=1b646761f2)
[English](https://mepodcastforum.us19.list-manage.com/subscribe/post?u=effbe51b005308df15c77177b&id=a61036f39e)

Join us on [Slack](https://join.slack.com/t/mepodcastforum/shared_invite/enQtNDQ2MjIwNjk4MzU3LTM3YWU4MzAzMmYyNGJjNjViNjUxNGIzM2IzYTc5Y2YwMDA0ODQ4ZGJlYzkwNzFlNTdjYTZmM2YzMjQ4YzE2ZGI)
<img width="825" alt="screen shot 2018-12-30 at 10 42 21 am" src="https://user-images.githubusercontent.com/45941301/50550171-9a138200-0c1f-11e9-8ef2-1433df2d8b65.png">

**Comment by rtaibah** [comment]
Done.
