### ISSUE TITLE
Edit Gallery description

### ISSUE THREAD

**Issue by kerningcultures** [mstdfr/mefp-website#5]
Change "MEPF 2018 Gallery" copy to:

**Past Forums**
We hosted the first-ever formal gathering of Middle East podcasters in September 2018 in Dubai. Make sure to catch our next event. Sign up for our [newsletter.](https://mepodcastforum.us19.list-manage.com/subscribe/post?u=effbe51b005308df15c77177b&id=a61036f39e) 
<img width="799" alt="screen shot 2018-12-30 at 10 43 46 am" src="https://user-images.githubusercontent.com/45941301/50550183-cc24e400-0c1f-11e9-8a3e-e640fc194604.png">

**Comment by rtaibah** [comment]
Done.
