### ISSUE TITLE
Edit Newsletter subscription (not on website, Mailchimp widget)

### ISSUE THREAD

**Issue by kerningcultures** [mstdfr/mefp-website#6]
Remove :
-Birthday
- Full Name

Newsletter subscription current link:

 https://mepodcastforum.us19.list-manage.com/subscribe/post?u=effbe51b005308df15c77177b&id=a61036f39e
<img width="762" alt="screen shot 2018-12-30 at 10 45 13 am" src="https://user-images.githubusercontent.com/45941301/50550194-01313680-0c20-11e9-9277-bccdb7ba56b5.png">

**Comment by rtaibah** [comment]
@kerningcultures I am gonna need login info for Mail Chimp.

**Comment by rtaibah** [comment]
Done.
