### ISSUE TITLE
Edit Meta tagline for website

### ISSUE THREAD

**Issue by kerningcultures** [mstdfr/mefp-website#9]
Change from "Website for first annual Middle East Podcast forum" to 
Where Middle East podcasters connect, share, and grow together! 

<img width="466" alt="screen shot 2019-02-25 at 5 43 13 am" src="https://user-images.githubusercontent.com/45941301/53341431-6459e500-38c0-11e9-914f-7f97a5a2070b.png">

**Comment by rtaibah** [comment]
fixed
